# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'NewsOrgApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for NewsOrgApp
   pod 'SDWebImage'
   pod 'ReachabilitySwift'
   pod 'MBProgressHUD', '~> 1.1.0'

  target 'NewsOrgAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'NewsOrgAppUITests' do
    # Pods for testing
  end

end
